routes/web.php
<?php

use App\Http\Controllers\FollowController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\TimelineController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('login');
});

/**
 * Route untuk menangani user
 * yang belom terAutentikasi
 */
Route::middleware(['guest'])->group(function () {

    /**
     * Register
     */
    Route::get('register', [RegisterController::class, 'index'])->name('register.index');
    Route::post('register', [RegisterController::class, 'store'])->name('register.store');

    /**
     * Login
     */
    Route::get('/login', [LoginController::class, 'index'])->name('login');
    Route::post('/login', [LoginController::class, 'auth'])->name('login.auth');

});

Route::middleware(['auth'])->group(function () {

    /**
     * Profile
     */

    Route::resource('profile', ProfileController::class);


    /**
     * Posts
     */
    Route::resource('/post', PostController::class);
    Route::get('/post/{id}', 'PostController@show')->name('post.show');

    /**
     * Timeline
     */
    Route::get('timeline', [TimelineController::class, 'index'])->name('timeline.index');

    /**
     * Follow
     */
    Route::post('follow/{id}/user', [FollowController::class, 'followUser'])->name('follow.user');
    Route::delete('follow/{id}/user', [FollowController::class, 'unfollowUser'])->name('unfollow.user');

    /**
     * Likes
     */
    Route::get('like/{id}', [LikeController::class, 'likePost'])->name('like.post');

    /**
     * List Followers
     */
    Route::get('/follow/{id}/list', [FollowController::class,'followList'])->name('follow.list');
    Route::get('/following/{id}/list', [FollowController::class,'followedList'])->name('following.list');

    /**
     * Search
     */
    Route::get('search', [SearchController::class, 'searchUser'])->name('search.user');


    /**
     * Get User Profile
     */

    Route::get('/{profile}', [ProfileController::class, 'profileData'])->name('profile.data');

    

    /**
     * Comment
     */
    Route::post('/comment', 'CommentController@index');
});

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Models\Follow;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authUser = Auth::id();

        $total_follow = User::find($authUser);
        $total_follow_process = $total_follow->follow->count();
        $total_followed_process = $total_follow->followed->count();

        $profile_details = User::find($authUser);
        $profile_details_process = $profile_details->profile;

        $post_list = Post::where('user_id', $authUser)
            ->orderBy('created_at', 'DESC')
            ->get();

        return view('page.profile.index', compact('total_follow_process', 'profile_details_process', 'total_followed_process', 'post_list'));
    }

    public function profileData($profile)
    {

        $authUser = Auth::id();

        $user = User::select('*')->where('name', $profile)->first();

        if ($user === null) {
            return redirect('profile');
        }

        $total_follow_process = $user->follow->count();
        $total_followed_process = $user->followed->count();

        $check_followed = Follow::where('user_id', $authUser)
            ->where('followed_id', $user->id)
            ->get()
            ->isEmpty();

        $profile_details_process = $user->profile;

        return view('page.profile.indexID', compact('total_follow_process', 'profile_details_process', 'total_followed_process', 'check_followed'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/page/profile/index.blade.php
@extends('template.master')
@section('title', 'Index')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Profile Details</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Profile</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-9">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">New Post</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
                          @csrf
                            <div class="form-group">
                                <label for="inputDescription">Describe Your Experience</label>
                                <textarea id="inputDescription" name="body" placeholder="What experience would you share?"
                                    class="form-control" rows="4"
                                    style="margin-top: 0px; margin-bottom: 0px; height: 141px;"></textarea>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputFile">Post Picture</label>
                                <div class="input-group">
                                  <div class="custom-file">
                        
                                    <input type="file" name="file" id="" class=""><br>
                                    
                                  </div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary">Show Picture</button>

                        </form>

                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <div class="image">
                                @if ($profile_details_process->photo_profile == '')
                                    <img src="https://ui-avatars.com/api/?name={{ $profile_details_process->full_name }}"
                                        class="img-circle elevation-2">
                                @else
                                    <img src="{{ $profile_details_process->photo_profile }}"
                                        class="img-circle elevation-2">
                                @endif
                            </div>
                        </div>

                        <h3 class="profile-username text-center">{{ $profile_details_process->full_name }}</h3>

                        <p class="text-muted text-center">{{ $profile_details_process->bio }}</p>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b><a href="{{ route('follow.list', $profile_details_process->id) }}"> Followers </a></b>
                                <a class="float-right">{{ $total_followed_process }}</a>
                            </li>
                            <li class="list-group-item">
                                <b><a href="{{ route('following.list', $profile_details_process->id) }}"> Following
                                    </a></b> <a class="float-right">{{ $total_follow_process }}</a>
                            </li>
                        </ul>

                        <a href="#" class="btn btn-primary btn-block"><b>Edit Profile</b></a>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <!-- About Me Box -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header p-2">
                        List Post
                    </div>
                    <div class="card-body">
                        @foreach ($post_list as $item)
                            <div class="post">
                                <div class="user-block">
                                    <div class="image">
                                        @if ($profile_details_process->photo_profile == '')
                                            <img src="https://ui-avatars.com/api/?name={{ $profile_details_process->full_name }}"
                                                class="img-circle elevation-2">
                                        @else
                                            <img src="{{ $profile_details_process->photo_profile }}"
                                                class="img-circle elevation-2">
                                        @endif
                                    </div>
                                    <span class="username">
                                        <a href="#">{{ $profile_details_process->full_name }}</a>
                                        <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
                                    </span>
                                    <span
                                        class="description">{{ Carbon\Carbon::parse($item->created_at)->diffForHumans() }}</span>
                                </div>
                                <!-- /.user-block -->
                                <p>
                                    {{ $item->body }}
                                </p>

                                @if (!empty($item->picture))
                                <img class="img-fluid pad" src="{{ Storage::url($item->picture) }}" alt="Photo">
                                @else
                                    
                                @endif

                                <p>
                                    <a href="#" class="link-black text-sm mr-2"><i class="fas fa-share mr-1"></i> Share</a>
                                    <a href="#" class="link-black text-sm"><i class="far fa-thumbs-up mr-1"></i> Like</a>
                                    <span class="float-right">
                                        <a href="/comment" class="link-black text-sm">
                                            <i class="far fa-comments mr-1"></i> Comments
                                        </a>
                                    </span>
                                </p>
                            </div>

                        @endforeach

                    </div><!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
@endsection

resources/views/page/profile/indexID.blade.php
@extends('template.master')
@section('title', 'Index')

@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Profile {{ $profile_details_process->full_name }}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Profile</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">

                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">
                        <div class="text-center">
                            <div class="image">
                                @if ($profile_details_process->photo_profile == '')
                                    <img src="https://ui-avatars.com/api/?name={{ $profile_details_process->full_name }}"
                                        class="img-circle elevation-2">
                                @else
                                    <img src="{{ $profile_details_process->photo_profile }}"
                                        class="img-circle elevation-2">
                                @endif
                                <img src="" class="img-circle elevation-2">
                            </div>
                        </div>

                        <h3 class="profile-username text-center">{{ $profile_details_process->full_name }}</h3>
                        <input type="hidden" name="user_id" value="{{ $profile_details_process->id }}">
                        <p class="text-muted text-center">{{ $profile_details_process->bio }}</p>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b><a href="{{ route('follow.list', $profile_details_process->id) }}"> Followers </a></b> <a class="float-right">{{ $total_followed_process }}</a>
                            </li>
                            <li class="list-group-item">
                                <b><a href="{{ route('following.list', $profile_details_process->id) }}"> Following </a></b> <a class="float-right">{{ $total_follow_process }}</a>
                            </li>
                        </ul>

                        @if ($check_followed)
                            <form action="{{ route('follow.user', $profile_details_process->id) }}" method="post">
                                @csrf

                                <button type="submit" class="btn btn-primary btn-block">Follow</button>
                            </form>

                        @else
                            <form action="{{ route('unfollow.user', $profile_details_process->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-primary btn-block">Unfollow</button>
                            </form>

                        @endif
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

                <!-- About Me Box -->

                <!-- /.card -->
            </div>
            <!-- /.col -->
            <div class="col-md-9">

                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
@endsection